version: "3.9"

services:
  e-commerce-api:
    image: csluispaulo/e-ecommerce-api
    container_name: e-commerce-api
    restart: always
    environment:
      DB_HOST: db-mysql
    ports:
      - "8080:8080"
    networks:
      - ecommerce-network
    depends_on:
      db-mysql:
        condition: service_healthy

  db-mysql:
    image: mysql:8.0
    container_name: db-mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3306:3306"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge