spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3306}/loja?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    open-in-view: false

  flyway:
    locations: classpath:db/migration,classpath:db/testdata